version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://username:password@mongo:27017/
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    links:
      - mongodb

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
  backend:
    build: ./backend
    ports:
      - 3000:3000
    networks:
      - mongo-compose-network

volumes:
  mongodb_data:

networks:
  mongo-compose-network:
    driver: bridge
