apiVersion: v1
kind: Secret
metadata:
  name: backend-test-secret
type: Opaque
data:
  MONGO_URL: ""
  PORT: ""
  API_KEY: ""
  RABBIT_MQ_URL: ""
  JWT_SECRET: ""
  JWT_EXPIRATION_TIME: ""
  LOGGER: ""
  REDIS_URL: ""