apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-test
  template:
    metadata:
      labels:
        app: backend-test
    spec:
      containers:
      - name: backend-test
        image: backend-test:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: "mongodb://username:password@localhost:27017/"
        - name: PORT
          value: "3001"
        - name: API_KEY
          value: "KEY_WORD"
        - name: RABBIT_MQ_URL
          value: "amqp://username:password@localhost:5672"
        - name: JWT_SECRET
          value: "SECRET_WORD"
        - name: JWT_EXPIRATION_TIME
          value: "1h"
        - name: LOGGER
          value: "ON"
        - name: REDIS_URL
          value: "redis://localhost:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-test-service
spec:
  selector:
    app: backend-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
